server:
  port: 8089
spring:
  datasource:
    url: jdbc:h2:mem:sdw2023
    username: sdw2023
    password:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
